tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot:
      model: transformer/generator
      model_file: zoo:msc/blender3B_1024/model
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page
